### ISSUE TITLE
Issue badgeに環境を追加して欲しい

### ISSUE THREAD

**Issue by eggplants** [VOICEVOX/voicevox#579]
## 内容

- Windows
- Mac
- Linux

のように、どの環境についてのIssueなのかを一目で見られるとありがたいです。(環境に依存しないものはAnywhereとか?)

### Pros 良くなる点

Badgeで環境ごとにIssueをフィルタでき、環境ごとに取り組むべきIssueがわかりやすくなる

### Cons 悪くなる点

Badgeを付けていくのが面倒

**Comment by y-chan** [comment]
なるほど、これは面白く、かつ良い提案だなと思います。

人的作業を省く手法として、一旦正確性を無視し、Issueが立った時に内容に含まれる単語(Windows/Mac/Linuxなど)で自動的に判別してラベル付けを行えるラベラー(Pull Request LabelerのIssue版)の導入できるかなと思いました。
ただ、Issueを立てる人が正確にOS名などを記載しなかった場合は、残念ながら上手く行きません...(とはいえ、少しは楽になるかなと思います)

ラベリングはオーナーのHiroshibaさんだけでなく、私たちレビュワーにも権限がありますので一旦人的リソースを気にする必要は無いかなとも思いますが、ラベラーの併用もすれば、メンテナンス性は上がるのかなと思いました。

**Comment by eggplants** [comment]
https://github.com/github/issue-labeler

`.github/labeler.yml`

```yml
mac:
    - '(mac|MAC|Mac|マック)'
linux:
    - '(linux|Linux|リナックス)'
win:
    - '(win|WIN|Win|ウィンドウズ)(dows|DOWS)?'
```

`.github/workflows/labeler.yml`

```yml
name: "Issue Labeler"
on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
```

**Comment by y-chan** [comment]
おお、良いと思います！！！

まだ正式にラベラーを導入すると決まった訳では無いですが、せっかくなのでPull Requestにして貰えますでしょうか...?

**Comment by eggplants** [comment]
これ、ラベルが[labels](https://github.com/VOICEVOX/voicevox/labels)に未定義だとどうなるんでしょうか

**Comment by eggplants** [comment]
`UnhandledPromiseRejectionWarning: HttpError: Label does not exist`になるっぽいのでlabelsに追加していただけるとありがたいです。

**Comment by y-chan** [comment]
なるほど、ラベルがない時はエラーを起こすのですね、検証ありがとうございます...!

Pull Requestをマージすることになった場合に同時に作業することにすると良いかなと思いました。

**Comment by MT224244** [comment]
OS名に関しては、Issueテンプレートの「OSの種類/ディストリ/バージョン」にチェックボックスを用意する等すれば入力してくれやすくなるかもしれません。

```md
## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

<!--
なるべく詳しく書いてください 記述例:
*   Windows 10 Pro 64bit (10.0.10586)
*   macOS Sierra
*   Linux fedora 23 64bit
*   Others
-->
```

**Comment by eggplants** [comment]
いいですね。

```yml
mac:
    - '\[x\] macOS'
linux:
    - '\[x\] Linux'
win:
    - '\[x\] Windows'
```
でラベリングの正確度を上げられそうです。
