### ISSUE TITLE
Mac：初回起動時の署名なしによるgatekeeperに止められる問題をなんとかする

### ISSUE THREAD

**Issue by Apple-Yuki** [VOICEVOX/voicevox#598]
## 内容

初回起動時の署名なしによるgatekeeperに止められる問題をなんとかする

### Pros 良くなる点

初めてダウンロードした人などがめんどくさいセキュリティー解除する手間を削減できる

### 実現方法

おそらく以下のjobをActionに組み込めれば署名されるはず。（**多分**）
```
jobs:
  build-mac:
    name: build
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Workaround: By doing this, if a system dialog around the keychain comes up, for example, the job will not proceed and will spend time until the default timeout.
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.1
      # Create: a freely usable keychain
      - run: security create-keychain -p password my.keychain
      # Set:default Keychain
      - run: security default-keychain -s my.keychain
      # Unlock:p12 so that it can be imported
      - run: security unlock-keychain -p password my.keychain
      # Don't lock your keychain with timeouts, etc
      - run: security set-keychain-settings my.keychain
      # Import: the necessary certificates, etc. The -A option is an option that can be used from any program.
      # In fact, p12 is actually obtained from an external source, but it is written as if it were local for clarity.
      - run: security import ./certs/macDeveloperIDApplication.p12 -k my.keychain -A -P ${{ secrets.P12PASS }}
      - run: security import ./certs/macDeveloperIDInstaller.p12 -k my.keychain -A -P ${{ secrets.P12PASS }}
      - run: security import ./certs/developerIdApplication.p12 -k my.keychain -A -P ${{ secrets.P12PASS }}
      - run: security import ./certs/developerIDInstaller.p12 -k my.keychain -A -P ${{ secrets.P12PASS }}
      # Allow access to Keychain from codesign
      - run: "security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k password my.keychain"
      - run: security list-keychains -s my.keychain
      - run: security find-identity -v
      - run: npm ci
      - name: Build App
        timeout-minutes: 15
        run: npm run build
      - run: echo DONE!
      # この後はリリースしたりの処理にしてください。
```

参考：
[electronアプリの署名・公証を自動化する](https://kent-and-co.com/866/)
[macOS向けにElectronアプリケーションの署名(code signing)・公証(notarization)をする](https://qiita.com/TomoyukiAota/items/6b81b4126058e7fd4099)

## VOICEVOXのバージョン

0.9.3

## OSの種類/ディストリ/バージョン

- [x ] macOS
