### ISSUE TITLE
DirectML対応版ビルドを追加する

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#775]
## 内容

VOICEVOXのコア・エンジンにDirectML版ビルドが追加されました！ （thx @y-chan @Oyaki122 ）

- https://github.com/VOICEVOX/voicevox_engine/pull/367

これに伴い、VOICEVOXエディタもDirectML対応版をビルド可能になったので、issue化してみました。

### Pros 良くなる点

AMD製GPUなどでも高速に音声合成できるかも？

### Cons 悪くなる点

特になし

### 実現方法

とりあえずDirectML版ビルドを追加するのが良いのかなと思っています。

## その他

昔のこちらのissueとも関連がありそうだったのでリンクしてみます

- https://github.com/VOICEVOX/voicevox/issues/686

@cyatarow さん、ご興味あったりされますか･･･？👀

**Comment by cyatarow** [comment]
ぜひ協力したいです。
どうすればDirectML版をビルドできますか?

私のPC環境は以下の通りです。
CPU: AMD Ryzen 5 2600
MEM: DDR4-2400 24GB
GPU: NVIDIA GeForce GT 1030

**Comment by cyatarow** [comment]
DirectML版エンジン(0.12.preview-0)のファイル群を、VOICEVOXのインストールディレクトリに上書きコピーすればいいんですか?

**Comment by y-chan** [comment]
@cyatarow こちら、どこかで詰まっている感じでしょうか👀
分からないところがある・対応が難しそうだと感じた等あれば、こちらでも引き受けられるかなと思います。
とりあえず現状を教えていただけると大変助かります🙏

**Comment by cyatarow** [comment]
VOICEVOXをフォークし、[リリースを作ってみたのですが](https://github.com/cyatarow/voicevox/releases/tag/0.12.0-prev)上手くいきません。
やり方が間違っているのでしょうか?
実のところ、ビルドのやり方をよく知りません。

**Comment by y-chan** [comment]
ちょっと変ですね...
リポジトリのActionsタブから、build workflowを手動実行するのもダメそうでしょうか...?
![image](https://user-images.githubusercontent.com/34832037/162629861-66b56b75-1105-4099-b0b5-ac72a287a391.png)

**Comment by cyatarow** [comment]
@y-chan
Build workflowを手動実行してから、リリースを作り直したらファイルができました!
Assets内のどのファイルを使えば良いでしょうか?

**Comment by y-chan** [comment]
> `windows-directml-prepackage`などと書くのでしょうか?

はい、そのような感じで大丈夫です！
CPUのものをコピーして、`cpu`を`directml`に書き換えれば大体は動くと思います(ちゃんと確認してないので、予想ですが...)

**Comment by y-chan** [comment]
良さそうです！！！
ただ、あと少しだけ変更していただけると助かります...!(コメントの編集なので、動作には影響しませんが...)

以下のような記述(`Replace package name & version`ステップ)が2か所ほどあるはずです(以下は双方に完全一致するものではなく、詳細に書かれている片方の記述です)
```yaml
      # NOTE: If the CPU/GPU builds have the same package name,
      #       the NSIS installers and the 7z files have duplicate names.
      #       For Linux, If they have the same product name,
      #       the AppImages have duplicate names.
      #       Files with the same name cannot be uploaded to a single GitHub Release,
      #       so different package/product names should be used for CPU/GPU builds.
      - name: Replace package name & version
        shell: bash
        run: |
          # GPU: "name": "voicevox" => "name": "voicevox"
          # CPU: "name": "voicevox" => "name": "voicevox-cpu"
          "${{ matrix.sed_name }}" -i 's/"name": "voicevox"/"name": "${{ matrix.package_name }}"/' package.json
          # "${{ matrix.sed_name }}" -i 's/productName: "VOICEVOX"/productName: "${{ matrix.product_name }}"/' vue.config.js
```

これを以下のようにしていただけると助かります
```yaml
      # NOTE: If the CPU/DirectML/GPU builds have the same package name,
      #       the NSIS installers and the 7z files have duplicate names.
      #       For Linux, If they have the same product name,
      #       the AppImages have duplicate names.
      #       Files with the same name cannot be uploaded to a single GitHub Release,
      #       so different package/product names should be used for CPU/DirectML/GPU builds.
      - name: Replace package name & version
        shell: bash
        run: |
          # GPU: "name": "voicevox" => "name": "voicevox"
          # CPU: "name": "voicevox" => "name": "voicevox-cpu"
          # DirectML: "name": "voicevox" => "name": "voicevox-directml"
          "${{ matrix.sed_name }}" -i 's/"name": "voicevox"/"name": "${{ matrix.package_name }}"/' package.json
          # "${{ matrix.sed_name }}" -i 's/productName: "VOICEVOX"/productName: "${{ matrix.product_name }}"/' vue.config.js
```

変更箇所をピックアップしてみると以下のような感じです
```diff
-      # NOTE: If the CPU/GPU builds have the same package name,
+      # NOTE: If the CPU/DirectML/GPU builds have the same package name,
      #       the NSIS installers and the 7z files have duplicate names.
      #       For Linux, If they have the same product name,
      #       the AppImages have duplicate names.
      #       Files with the same name cannot be uploaded to a single GitHub Release,
-      #       so different package/product names should be used for CPU/GPU builds.
+      #       so different package/product names should be used for CPU/DirectML/GPU builds.
      - name: Replace package name & version
        shell: bash
        run: |
          # GPU: "name": "voicevox" => "name": "voicevox"
          # CPU: "name": "voicevox" => "name": "voicevox-cpu"
+          # DirectML: "name": "voicevox" => "name": "voicevox-directml"
          "${{ matrix.sed_name }}" -i 's/"name": "voicevox"/"name": "${{ matrix.package_name }}"/' package.json
          # "${{ matrix.sed_name }}" -i 's/productName: "VOICEVOX"/productName: "${{ matrix.product_name }}"/' vue.config.js
```
